services:
  control-hub-frontend:
    image: piandarduinoguy/control-hub-frontend:20220813
    ports:
      - 8080:8080
    environment:
      SECURITY_MICRO_SERVICE_BASE_URL: http://192.168.3.184:8082/security