services:
  control-hub-frontend:
    image: piandarduinoguy/control-hub-frontend:20220813
    ports:
      - 8080:8080
    networks:
      - security-network
networks:
  security-network:
    external: true
    name: security-network
    driver: overlay