services:
  security-micro-service:
    image: piandarduinoguy/security-micro-service:20220813
    ports:
      - 8082:8082
    volumes:
      - security-micro-service:/security-micro-service/resources
    networks:
      - security-network
    restart: always
  rabbitmq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - security-network
  control-hub-frontend:
    image: piandarduinoguy/control-hub-frontend:20220813
    ports:
      - 8080:8080
    environment:
      SECURITY_MICRO_SERVICE_BASE_URL: http://192.168.3.184:8082/security
    restart: always

volumes:
  security-micro-service:

networks:
  security-network:
    external: true
    name: security-network
    driver: overlay